name: intent_comm_nav
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - numpy==1.26.4
      - jax==0.4.23
      - jaxlib==0.4.23
      - matplotlib==3.5.3
      - imageio==2.37.2
      - scipy>=1.9
      - ml-dtypes>=0.2.0
      - opt-einsum>=3.3.0

